/**
 * Created by cicean on 9/2/2016.
 * 389. Find the Difference  QuestionEditorial Solution  My Submissions
 Total Accepted: 11484
 Total Submissions: 23961
 Difficulty: Easy
 Given two strings s and t which consist of only lowercase letters.

 String t is generated by random shuffling string s and then add one more letter at a random position.

 Find the letter that was added in t.

 Example:

 Input:
 s = "abcd"
 t = "abcde"

 Output:
 e

 Explanation:
 'e' is the letter that was added.
 Hide Company Tags Google
 Hide Tags Hash Table Bit Manipulation
 Hide Similar Problems (E) Single Number

 */
public class FindtheDifference {

    /**
     * 有两个字符串S和T，T是S打乱后多加一个字符，要找出这个不同的字符来。

     嗯，这个问题其实就是异或，除了T多的那个字符外，都可以在异或中消除，不多说，很简单
     */
    public char findTheDifference(String s, String t) {
        char tmp = 0x00;
        for(int i=0;i<s.length();i++)
            tmp =(char)( tmp ^ s.charAt(i));
        for(int i=0;i<t.length();i++)
            tmp = (char)(tmp ^ t.charAt(i));
        return tmp;
    }

}
